version: '2.1'

# homodaba docker

services:
    static-build:
        extends:
            service: static-build
            file: docker-compose.base.yml
    app:
        extends:
            service: app
            file: docker-compose.base.yml
        environment:
            DJANGO_DEBUG: 1
            SECRET_KEY: ${SECRET_KEY}
            SQLITE_ROOT: /opt/app/sqlite
        ports:
            - "127.0.0.1:8000:8000"