version: '2.0'

# homodaba docker
# Version con Elasticsearch.

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        restart: always
        environment:
            - discovery.type=single-node
    proxy:
        build:
            context: .
            dockerfile: docker/proxy/Dockerfile
        ports:
            - "8000:80"
        restart: always
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        restart: always
        env_file:
            - .env
        environment:
          - ES_DSL_HOSTS=elasticsearch:9200
        volumes:
            - ${HOST_SQLITE}:/opt/app/sqlite
            - ${HOST_IMPORT}:/opt/app/import
