version: '2.1'

# homodaba docker

services:
    proxy:
        extends:
            service: proxy
            file: docker-compose.base.yml
    app:
        extends:
            service: app
            file: docker-compose.base.yml