version: '2.1'

# homodaba docker

services:
    proxy:
        build:
            context: .
            dockerfile: docker/proxy/Dockerfile
        ports:
            - "8000:80"
        restart: always
    mysql-db:
        image: mysql:5.7
        volumes:
          - ${MYSQL_DATA_VOL:-DEFAULT_SQL_PATH}:/var/lib/mysql
        expose:
            - 3306
        environment:
          - MYSQL_DATABASE=${DATABASE_NAME:-homodaba}
          - MYSQL_USER=${DATABASE_USER:-homodaba_user}
          - MYSQL_PASSWORD=${DATABASE_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        env_file:
          - .env
        command: ['--character-set-server=utf8']
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                # ver docker/app/Dockerfile para mas info de estas variables
                DATABASE_ENGINE: ${DATABASE_ENGINE:-sqlite}
                ELASTICSEARCH: ${ELASTICSEARCH:-false}
                TELEGRAM: ${TELEGRAM:-false}
        restart: always
        env_file:
            - .env
        volumes:
            - ${HOST_SQLITE}:/opt/app/sqlite
            - ${HOST_IMPORT}:/opt/app/import

