version: '2.1'

# homodaba docker
# Version MySQL for development 

services:
    dev-gulp:
        image: node:10
        working_dir: /src
        command: ["/bin/sh", "-c", "npm install && npm run build:watch"]
        volumes:
            - ./static:/src
    dev-db:
        image: mysql:5.7
        volumes:
            - ${MYSQL_DATA_VOL?Variable not set}:/var/lib/mysql
        expose:
            - 3306
        environment:
          - MYSQL_DATABASE=${DATABASE_NAME:-homodaba}
          - MYSQL_USER=${DATABASE_USER:-homodaba_user}
          - MYSQL_PASSWORD=${DATABASE_PASSWORD?Variable not set}
          - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD?Variable not set}
        env_file:
          - .env
        command: ['--character-set-server=utf8']
    dev-app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
            args:
                db_engine: mysql
        ports:
            - "8000:8000"
        environment:
            - DJANGO_DEBUG=1
            - DATABASE_ENGINE=${DATABASE_ENGINE:-mysql}
            - DATABASE_HOST=${DATABASE_HOST:-dev-db}
            - DATABASE_NAME=${DATABASE_NAME:-homodaba}
            - DATABASE_USER=${DATABASE_USER:-homodaba_user}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD?Variable not set}
        env_file:
            - .env
        volumes:
            - ./homodaba:/opt/app/homodaba
            - ./static/build:/opt/app/static/build
            - ${HOST_IMPORT}:/opt/app/import
            - ${HOST_SQLITE}:/opt/app/sqlite
        depends_on:
            - dev-db
