# Generated by Django 3.1 on 2020-09-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretag',
            options={'verbose_name': 'género', 'verbose_name_plural': 'géneros'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'película', 'verbose_name_plural': 'películas'},
        ),
        migrations.AlterModelOptions(
            name='movieperson',
            options={'verbose_name': 'reparto', 'verbose_name_plural': 'repartos'},
        ),
        migrations.AlterModelOptions(
            name='moviestoragetype',
            options={'verbose_name': 'tipo de almacenamiento', 'verbose_name_plural': 'tipos de almacenamiento'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'etiqueta', 'verbose_name_plural': 'etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='titleaka',
            options={'verbose_name': 'título conocido (aka)', 'verbose_name_plural': 'títulos conocidos (akas)'},
        ),
    ]
