# Generated by Django 3.1 on 2020-09-07 04:43

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200905_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Géneros'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='movieperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person', verbose_name='participante'),
        ),
        migrations.AlterField(
            model_name='moviestoragetype',
            name='is_original',
            field=models.BooleanField(default=True, verbose_name='Original'),
        ),
        migrations.AlterField(
            model_name='moviestoragetype',
            name='media_format',
            field=models.CharField(choices=[('AVI', 'AVI'), ('BLURAY', 'BLURAY'), ('BLURAY-ISO', 'BLURAY-ISO'), ('DVD', 'DVD'), ('DVD-ISO', 'DVD-ISO'), ('ISO', 'ISO'), ('M2TS', 'M2TS'), ('M4V', 'M4V'), ('MKV', 'MKV'), ('MP4', 'MP4'), ('ULTRA-BLURAY', 'ULTRA-BLURAY')], default='DVD', max_length=20, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='moviestoragetype',
            name='storage_type',
            field=models.CharField(choices=[('hard-drive', 'Disco duro'), ('net-share', 'Compartido de red'), ('dvd', 'DVD'), ('bluray', 'BLURAY'), ('ultra-bluray', 'ULTRA BLURAY'), ('vhs', 'VHS')], default='dvd', max_length=20, verbose_name='Tipo de almacenamiento'),
        ),
    ]
