# Generated by Django 3.1 on 2020-09-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200908_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRatingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'calificación de edad',
                'verbose_name_plural': 'calificaciones de edad',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='content_rating_systems',
            field=models.ManyToManyField(to='data.ContentRatingTag'),
        ),
    ]
