# Generated by Django 3.1 on 2020-09-07 05:00

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200907_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_akas',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Otros títulos conocidos (aka)'),
        ),
    ]
