# Generated by Django 3.1 on 2021-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200910_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePersonDirectorProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.movieperson',),
        ),
        migrations.AlterModelOptions(
            name='contentratingtag',
            options={'verbose_name': 'clasificación de edad', 'verbose_name_plural': 'clasificaciones de edad'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_raw_data',
            field=models.TextField(blank=True, null=True, verbose_name='RAW data IMDB'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(through='data.MoviePersonDirectorProxy', to='data.Person'),
        ),
    ]
