# Generated by Django 3.1 on 2021-07-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210703_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='movies_as_director',
            field=models.ManyToManyField(through='data.MoviePersonDirectorProxy', to='data.Movie'),
        ),
    ]
