# Generated by Django 3.1 on 2021-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_person_movies_as_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, null=True, verbose_name='IMDB ID')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='RAW DATA IMDB')),
            ],
        ),
    ]
