# Generated by Django 3.1 on 2021-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210707_1933'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imdbcache',
            index=models.Index(fields=['search_query'], name='imdbcache_search_query_idx'),
        ),
        migrations.AddIndex(
            model_name='imdbcache',
            index=models.Index(fields=['imdb_id'], name='imdbcache_imdb_id_idx'),
        ),
    ]
