# Generated by Django 3.1 on 2021-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210725_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleaka',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
