# Generated by Django 3.1 on 2021-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_titleaka_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(to='data.Country'),
        ),
    ]
