# Generated by Django 3.1 on 2021-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210730_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'etiqueta de usario',
                'verbose_name_plural': 'etiquetas de usuario',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='user_tags',
            field=models.ManyToManyField(to='data.UserTag'),
        ),
    ]
