# Generated by Django 3.1 on 2021-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20210804_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviePersonDirectorProxy',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.AlterField(
            model_name='movie',
            name='content_rating_systems',
            field=models.ManyToManyField(blank=True, to='data.ContentRatingTag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='data.GenreTag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data.Tag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_tags',
            field=models.ManyToManyField(blank=True, to='data.UserTag'),
        ),
    ]
