# Generated by Django 3.1 on 2021-08-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_movie_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_raw_data',
        ),
        migrations.RemoveField(
            model_name='person',
            name='imdb_raw_data',
        ),
    ]
