# Generated by Django 3.1 on 2021-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20210808_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kind',
            field=models.CharField(choices=[('movie', 'Película'), ('naim-movie', 'Película (no dada de alta en imdb)'), ('tv series', 'Serie de television')], default='movie', max_length=20, verbose_name='Clase de pélicula'),
        ),
    ]
