# Generated by Django 5.2.8 on 2026-02-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20210811_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Entrada de Caché',
                'verbose_name_plural': 'Entradas de Caché',
            },
        ),
        migrations.DeleteModel(
            name='ImdbCache',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
    ]
