# Generated by Django 5.2.8 on 2026-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_cachetable_delete_imdbcache_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='TMDB ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='tmdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='IMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Título (Internacional)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_original',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Título (Original)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_preferred',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Título (Idioma preferido)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='canonical_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre (Canónico)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='IMDB ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre'),
        ),
    ]
