# Generated by Django 5.2.8 on 2026-02-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_movie_tmdb_id_person_tmdb_id_alter_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleaka',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
