# Generated by Django 5.2.8 on 2026-02-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_titleaka_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleaka',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
