# Generated by Django 5.2.8 on 2026-02-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_titleaka_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titleaka',
            old_name='language',
            new_name='title_type',
        ),
    ]
