# Generated by Django 5.2.8 on 2026-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_rename_language_titleaka_title_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachetable',
            name='id',
        ),
        migrations.AddField(
            model_name='cachetable',
            name='created',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cachetable',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
