# Generated by Django 5.2.8 on 2026-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_remove_cachetable_id_cachetable_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachetable',
            name='created',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
