version: '2.0'

# homodaba docker
# Version debug

services:
    debug-app:
        build:
            context: .
            dockerfile: docker/debug/Dockerfile
        ports:
           - "8000:8000"
        restart: always
        env_file:
            - .env
        volumes:
            - ${HOST_SQLITE}:/opt/app/sqlite
            - ${HOST_IMPORT}:/opt/app/import
