version: '2.1'

# homodaba docker:
# Version con Elastic search pero sin telegram bot (ver mas abajo si quieres ponerlo)

services:
    homodaba-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        hostname: homodaba-es-host
        container_name: homodaba-es-container
        restart: always
        environment:
            - discovery.type=single-node
    homodaba-app:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-app-host
        container_name: homodaba-app-container
        ports:
            - "8000:8000"
        restart: always
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - ES_DSL_HOSTS=homodaba-es-host
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        env_file:
            - ./.env
        volumes:
            - ${HOST_SQLITE:-./volumes/sqlite}:/opt/app/sqlite
            - ${HOST_STATIC:-./volumes/static}:/opt/app/static
            - ${HOST_IMPORT:-./volumes/import}:/opt/app/import
        command: /init-homodaba.sh
# Si quieres el bot de telegram solo tienes que:
#    1) Conseguir un token siguiendo a traves del botfather
#       https://core.telegram.org/bots#6-botfather
#    2) Con el token descomentar estas lineas y poner el token en la variable de
#       entorno TBOT_TOKEN
#    homodaba-tbot:
#        build: ./
#        image: homodaba:trunk
#        hostname: homodaba-tbot-host
#        container_name: homodaba-tbot-container
#        restart: always
#        environment:
#            - TBOT_TOKEN=${TBOT_TOKEN}
#        volumes:
#            - ./volumes/sqlite:/opt/app/sqlite
