version: '2.0'

# homodaba docker
# Version sin Elasticsearch.

services:
    homodaba-app:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-app-host
        container_name: homodaba-app-container
        ports:
            - "8000:8000"
        restart: always
        env_file:
          - .env
        volumes:
          - ${HOST_SQLITE}:/opt/app/sqlite
          - ${HOST_IMPORT}:/opt/app/import
          - ${HOST_STATIC}:/opt/app/static
        command: /init-homodaba.sh
