version: '2.0'

# homodaba docker:
# Version sin Elastic search

services:
    homodaba-app:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-app-host
        container_name: homodaba-app-container
        ports:
            - "8000:8000"
        restart: always
        env_file:
            - ./.env-no-es
        volumes:
            - ${HOST_SQLITE}:/opt/app/sqlite
            - ${HOST_IMPORT}:/opt/app/import
            - ${HOST_STATIC}:/opt/app/static
        command: /init-homodaba.sh
    homodaba-tbot:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-tbot-host
        container_name: homodaba-tbot-container
        restart: always
        env_file:
            - ./.env-no-es
        volumes:
            - ${HOST_SQLITE}:/opt/app/sqlite
        command: /init-homodaba-tbot.sh
