version: '2.0'

# homodaba docker:
# Version sin Elastic search

services:
    homodaba-app:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-app-host
        container_name: homodaba-app-container
        ports:
            - "8000:8000"
        restart: always
        env_file:
            - ./.env-no-es
        volumes:
            - ${HOST_SQLITE:-./volumes/sqlite}:/opt/app/sqlite
            - ${HOST_IMPORT:-./volumes/import}:/opt/app/import
            - ${HOST_STATIC:-./volumes/static}:/opt/app/static
        command: /init-homodaba.sh
    homodaba-tbot:
        build: ./
        image: homodaba:trunk
        hostname: homodaba-tbot-host
        container_name: homodaba-tbot-container
        restart: always
        env_file:
            - ./.env-no-es
        volumes:
            - ./volumes/sqlite:/opt/app/sqlite
        command: /init-homodaba-tbot.sh
