version: '2.0'

# homodaba docker
# Version for development

services:
    dev-gulp:
        image: node:10
        working_dir: /src
        command: ["/bin/sh", "-c", "npm install && npm run build:watch"]
        volumes:
            - ./static:/src
    dev-db:
        image: mysql:5.7
        volumes:
            - ${MYSQL_DATA_VOL}:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=homodaba
        env_file:
            - .env
    dev-app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DJANGO_DEBUG=1
            - DATABASE_ENGINE=mysql
            - DATABASE_HOST=dev-db
            - DATABASE_NAME=homodaba
            - DATABASE_USER=root
        env_file:
            - .env
        volumes:
            - ./homodaba:/opt/app/homodaba
            - ./static/build:/opt/app/homodaba/static/build
            - ${HOST_SQLITE}:/opt/app/sqlite
            - ${HOST_IMPORT}:/opt/app/import
