# Generated by Django 3.1 on 2021-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodi', '0002_kodihost_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodihost',
            name='host_url',
            field=models.CharField(help_text="Url completa a la administracion web de kodi, por ejemplo: 'http://kodi-host:8080' (OJO: Que no termine en /)", max_length=255, verbose_name='Host URL'),
        ),
    ]
